version: '3.1'

services:

  db:
    image: postgres
    restart: always
    expose: 
      - "5432"
    environment:
      POSTGRES_PASSWORD: "Irish#31"

  server:
    image: workout_server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

    